// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HoverPop: typeof import('./src/components/HoverPop.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    NavPop: typeof import('./src/components/NavPop.vue')['default']
    ProgressCircle: typeof import('./src/components/progressCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VolBtn1: typeof import('./src/components/volBtn1.vue')['default']
    VolBtn2: typeof import('./src/components/volBtn2.vue')['default']
  }
}

export {}
